name: UI E2E Tests

on:
  repository_dispatch:
    types:
      - "vercel.deployment.success"

jobs:
  e2e-tests:
    if: |
      github.event_name == 'repository_dispatch' &&
      github.event.client_payload.project.name == 'app-frontend-v3'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      # For now, we only need Chromium.
      - name: Install Playwright Browsers
        run: yarn playwright install chromium
      - name: Setup Synpress wallet cache
        # https://synpress.io/docs/guides/ci#ci
        run: xvfb-run yarn synpress ./e2e/wallet-setup
        env:
          E2E_DAPP_URL: ${{ github.event.client_payload.url }}
      - name: Run tests
        # https://synpress.io/docs/guides/ci#ci
        run: xvfb-run yarn test:e2e:headful
        env:
          E2E_DAPP_URL: ${{ github.event.client_payload.url }}
      - name: Archive Playwright report
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: playwright-report-headful
          path: |
            playwright-report/
          if-no-files-found: error
